#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-lSDL2 -lGLEW -lGL
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/SDL_OpenGL_OBJLoader

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O3 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-lSDL2 -lGLEW -lGL
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/SDL_OpenGL_OBJLoader

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/Camera.o $(OBJDIR_DEBUG)/src/GLShader.o $(OBJDIR_DEBUG)/src/Mesh.o $(OBJDIR_DEBUG)/src/OBJLoader.o $(OBJDIR_DEBUG)/src/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/Camera.o $(OBJDIR_RELEASE)/src/GLShader.o $(OBJDIR_RELEASE)/src/Mesh.o $(OBJDIR_RELEASE)/src/OBJLoader.o $(OBJDIR_RELEASE)/src/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Camera.cpp -o $(OBJDIR_DEBUG)/src/Camera.o

$(OBJDIR_DEBUG)/src/GLShader.o: src/GLShader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GLShader.cpp -o $(OBJDIR_DEBUG)/src/GLShader.o

$(OBJDIR_DEBUG)/src/Mesh.o: src/Mesh.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Mesh.cpp -o $(OBJDIR_DEBUG)/src/Mesh.o

$(OBJDIR_DEBUG)/src/OBJLoader.o: src/OBJLoader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/OBJLoader.cpp -o $(OBJDIR_DEBUG)/src/OBJLoader.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Camera.cpp -o $(OBJDIR_RELEASE)/src/Camera.o

$(OBJDIR_RELEASE)/src/GLShader.o: src/GLShader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GLShader.cpp -o $(OBJDIR_RELEASE)/src/GLShader.o

$(OBJDIR_RELEASE)/src/Mesh.o: src/Mesh.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Mesh.cpp -o $(OBJDIR_RELEASE)/src/Mesh.o

$(OBJDIR_RELEASE)/src/OBJLoader.o: src/OBJLoader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/OBJLoader.cpp -o $(OBJDIR_RELEASE)/src/OBJLoader.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

